Update sub-project Makefiles to support workspace target directories

diff --git a/cce-client/Makefile b/cce-client/Makefile
--- a/cce-client/Makefile
+++ b/cce-client/Makefile
@@ -5,9 +5,21 @@ build:
 
 install: build
 	mkdir -p ~/.local/bin
-	install -m 755 target/release/cce-client ~/.local/bin/cce-client
-	install -m 755 target/release/clearctl ~/.local/bin/clearctl
-	install -m 755 target/release/clear-inspector ~/.local/bin/clear-inspector
+	@if [ -f target/release/cce-client ]; then \
+		install -m 755 target/release/cce-client ~/.local/bin/cce-client; \
+		install -m 755 target/release/clearctl ~/.local/bin/clearctl; \
+		install -m 755 target/release/clear-inspector ~/.local/bin/clear-inspector; \
+	elif [ -f ../target/release/cce-client ]; then \
+		install -m 755 ../target/release/cce-client ~/.local/bin/cce-client; \
+		install -m 755 ../target/release/clearctl ~/.local/bin/clearctl; \
+		install -m 755 ../target/release/clear-inspector ~/.local/bin/clear-inspector; \
+	elif [ -f ../../target/release/cce-client ]; then \
+		install -m 755 ../../target/release/cce-client ~/.local/bin/cce-client; \
+		install -m 755 ../../target/release/clearctl ~/.local/bin/clearctl; \
+		install -m 755 ../../target/release/clear-inspector ~/.local/bin/clear-inspector; \
+	else \
+		echo "Error: cce-client binaries not found"; exit 1; \
+	fi
 
 run:
 	cargo run
diff --git a/cce-server/Makefile b/cce-server/Makefile
--- a/cce-server/Makefile
+++ b/cce-server/Makefile
@@ -5,7 +5,15 @@ build:
 
 install: build
 	mkdir -p ~/.local/bin
-	install -m 755 target/release/cce-server ~/.local/bin/cce-server
+	@if [ -f target/release/cce-server ]; then \
+		install -m 755 target/release/cce-server ~/.local/bin/cce-server; \
+	elif [ -f ../target/release/cce-server ]; then \
+		install -m 755 ../target/release/cce-server ~/.local/bin/cce-server; \
+	elif [ -f ../../target/release/cce-server ]; then \
+		install -m 755 ../../target/release/cce-server ~/.local/bin/cce-server; \
+	else \
+		echo "Error: cce-server binary not found"; exit 1; \
+	fi
 
 run:
 	cargo run
